version: '3.8'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      FLASK_ENV: development
      FLASK_APP: app
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      REACT_APP_API_BASE_URL: "http://localhost:5000"
networks:
  app-network:
    driver: bridge
