ARG PYTHON_VERSION=3.13
FROM python:${PYTHON_VERSION}-slim as base

WORKDIR /Backend

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
